title = "Ali Sareini"
description = "Ali Sareini's personal blog"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a>, I was just curious.
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "texify3"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2024"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true
enableInlineShortcodes = true

[sharingbuttons]
facebook = false
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = false
hackernews = true
telegram = false
